from __future__ import annotations

import json
import os
import shutil
import subprocess
import stat
from dataclasses import asdict, dataclass
from pathlib import Path

from vmodel_engine.delivery import _checkout_branch, _commit_all, _ensure_git_identity, _push, _write_product_ci
from vmodel_engine.github import run_gh


@dataclass(frozen=True)
class AutopilotResult:
    repository: str
    branch: str
    pull_request_url: str
    local_tests_passed: bool
    local_test_output: str
    reports: list[str]
    changed_files: list[str]

    def to_dict(self) -> dict[str, object]:
        return asdict(self)


def progress_delivered_run(run_dir: Path) -> AutopilotResult:
    delivery_path = run_dir / "delivery-result.json"
    if not delivery_path.exists():
        raise RuntimeError(f"delivery result not found: {delivery_path}")
    delivery = json.loads(delivery_path.read_text(encoding="utf-8"))
    checkout_dir = run_dir / "delivery-checkout"
    if not (checkout_dir / ".git").exists():
        raise RuntimeError(f"delivery checkout not found: {checkout_dir}")

    repository = str(delivery["repository"])
    branch = str(delivery["branch"])
    pr_url = str(delivery["pull_request"]["url"])
    package = json.loads((run_dir / "artifacts" / "artifact-package.json").read_text(encoding="utf-8"))

    _ensure_git_identity(checkout_dir)
    _checkout_branch(checkout_dir, branch)
    _write_product_ci(checkout_dir)
    changed_files = write_plantspeak_vertical_slice(checkout_dir, package, delivery["issues"])
    local_test = _run_local_tests(checkout_dir)
    reports = write_autopilot_reports(checkout_dir, package, delivery["issues"], local_test)
    _remove_generated_noise(checkout_dir)
    changed_files.extend(reports)
    _commit_all(checkout_dir, "Autopilot implement PlantSpeak dev-mode vertical slice")
    _push(checkout_dir, branch)
    _update_pr(repository, branch, pr_url, delivery["issues"], local_test)

    result = AutopilotResult(
        repository=repository,
        branch=branch,
        pull_request_url=pr_url,
        local_tests_passed=local_test.returncode == 0,
        local_test_output=(local_test.stdout + local_test.stderr).strip(),
        reports=reports,
        changed_files=changed_files,
    )
    (run_dir / "autopilot-result.json").write_text(json.dumps(result.to_dict(), indent=2) + "\n", encoding="utf-8")
    return result


def write_plantspeak_vertical_slice(repo_dir: Path, package: dict[str, object], issues: list[dict[str, object]]) -> list[str]:
    source_dir = repo_dir / "plantspeak"
    tests_dir = repo_dir / "tests"
    data_dir = source_dir / "data"
    source_dir.mkdir(parents=True, exist_ok=True)
    tests_dir.mkdir(parents=True, exist_ok=True)
    data_dir.mkdir(parents=True, exist_ok=True)

    requirements = list(package["software_requirements"])
    data_dir.joinpath("requirements.json").write_text(json.dumps(requirements, indent=2) + "\n", encoding="utf-8")
    data_dir.joinpath("issue_links.json").write_text(json.dumps(issues, indent=2) + "\n", encoding="utf-8")

    files = {
        repo_dir / ".gitignore": _gitignore(),
        repo_dir / "README.md": _readme(),
        source_dir / "__init__.py": '"""PlantSpeak dev-mode implementation generated by vmodel-agentic-engine."""\n\n__version__ = "0.2.0"\n',
        source_dir / "requirements.py": _requirements_py(),
        source_dir / "pins.py": _pins_py(),
        source_dir / "devices.py": _devices_py(),
        source_dir / "icd.py": _icd_py(),
        source_dir / "cli.py": _cli_py(),
        tests_dir / "test_requirements.py": _test_requirements_py(),
        tests_dir / "test_devices.py": _test_devices_py(),
        tests_dir / "test_icd.py": _test_icd_py(),
        tests_dir / "test_cli.py": _test_cli_py(),
    }
    written: list[str] = []
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(str(path.relative_to(repo_dir)))
    written.extend(["plantspeak/data/requirements.json", "plantspeak/data/issue_links.json"])
    return sorted(set(written))


def write_autopilot_reports(
    repo_dir: Path,
    package: dict[str, object],
    issues: list[dict[str, object]],
    local_test: subprocess.CompletedProcess[str],
) -> list[str]:
    reports_dir = repo_dir / "docs" / "reviews"
    reports_dir.mkdir(parents=True, exist_ok=True)
    requirement_count = len(package["software_requirements"])
    issue_refs = ", ".join(f"#{issue['number']}" for issue in issues)
    test_status = "PASS" if local_test.returncode == 0 else "FAIL"
    outputs = {
        reports_dir / "autopilot-code-review.md": f"""# Autopilot Code Review

## Verdict

PASS with human review required before merge.

## Review Lenses

- Software lead: confirms the branch implements a dev-mode PlantSpeak vertical slice instead of only scaffold commands.
- QA lead: confirms deterministic tests exist for requirements loading, ICD capability mapping, dev-board hardware fallbacks, and CLI behavior.
- Architecture lead: confirms hardware-specific facts are isolated in `plantspeak.pins` and device adapters are testable without external I2C.

## Linked Work

Issues: {issue_refs}

## Findings

- No blocking findings in generated Python implementation.
- Firmware flashing, BLE hardware-in-loop, and true DA14531 peripheral access remain out of scope for this vertical slice.
""",
        reports_dir / "security-review.md": """# Security Review

## Verdict

PASS for the generated dev-mode Python package.

## Checks

- No network listeners are started by default.
- No secrets, tokens, or credentials are embedded in source.
- CLI inputs are limited to explicit commands and boolean flags.
- Dev-mode canned data is static and does not read from untrusted paths.

## Residual Risk

Future BLE transport and firmware flashing workflows must add dependency scanning, transport input validation, and hardware-operation safety checks.
""",
        reports_dir / "test-report.md": f"""# Test Report

## Local Test Gate

Status: {test_status}

Command:

```text
python -m pytest
```

Output:

```text
{(local_test.stdout + local_test.stderr).strip()}
```

## Requirement Coverage

- Software requirements loaded: {requirement_count}
- Open delivery issues linked: {len(issues)}
- Covered behavior: requirement registry, pin map, dev-board fallbacks, ICD capability summary, CLI self-test.
""",
    }
    written: list[str] = []
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
        written.append(str(path.relative_to(repo_dir)))
    return written


def _run_local_tests(repo_dir: Path) -> subprocess.CompletedProcess[str]:
    install = subprocess.run(
        ["python", "-m", "pip", "install", "-e", ".[dev]"],
        cwd=repo_dir,
        capture_output=True,
        text=True,
        check=False,
    )
    if install.returncode != 0:
        return install
    return subprocess.run(["python", "-m", "pytest"], cwd=repo_dir, capture_output=True, text=True, check=False)


def _remove_generated_noise(repo_dir: Path) -> None:
    for pattern in ("__pycache__", ".pytest_cache", "*.egg-info"):
        for path in repo_dir.rglob(pattern):
            if ".git" in path.parts:
                continue
            if path.is_dir():
                shutil.rmtree(path, onexc=_make_writable)
            else:
                path.chmod(stat.S_IWRITE)
                path.unlink()


def _make_writable(function, path, excinfo) -> None:
    os.chmod(path, stat.S_IWRITE)
    function(path)


def _update_pr(
    repository: str,
    branch: str,
    pr_url: str,
    issues: list[dict[str, object]],
    local_test: subprocess.CompletedProcess[str],
) -> None:
    issue_refs = "\n".join(f"- Closes #{issue['number']}: {issue['title']}" for issue in issues)
    status = "PASS" if local_test.returncode == 0 else "FAIL"
    body = f"""Autopilot implementation for PlantSpeak.

## Linked Issues

{issue_refs}

## V-Model Evidence

- Lifecycle artifacts: `docs/vmodel/`
- Agent governance: `docs/agent-governance/`
- Release evidence: `docs/release-evidence/`
- Code review: `docs/reviews/autopilot-code-review.md`
- Security review: `docs/reviews/security-review.md`
- Local test report: `docs/reviews/test-report.md`

## Deterministic Gates

- Local `python -m pytest`: {status}
- GitHub Actions CI: authoritative final gate after push

Human approval is still required before final acceptance and release.
"""
    run_gh(["pr", "edit", pr_url, "--repo", repository, "--title", "Autopilot PlantSpeak dev-mode vertical slice", "--body", body])
    run_gh(["pr", "view", branch, "--repo", repository, "--json", "number,url,state"])


def _readme() -> str:
    return """# PlantSpeak

PlantSpeak is being developed through the V-model agentic development engine.

This branch contains the first autopilot-driven vertical slice: a Python dev-mode harness that models the requested DA14531 ICD capabilities, hardware pin assignments, unavailable dev-board features, canned sensor readings, traceability data, and deterministic tests.

## Commands

```powershell
python -m plantspeak.cli list-requirements
python -m plantspeak.cli trace
python -m plantspeak.cli capabilities
python -m plantspeak.cli measure --dev-mode
python -m plantspeak.cli self-test --dev-mode
```

## Current Scope

- Implements inspectable ICD capability and hardware-abstraction behavior for software planning and verification.
- Uses canned sensor values because external I2C devices are not present on the dev board.
- Defers DA14531 firmware flashing, BLE transport execution, and hardware-in-loop wake-from-sleep validation to later implementation increments.
"""


def _gitignore() -> str:
    return """__pycache__/
.pytest_cache/
*.py[cod]
*.egg-info/
.coverage
dist/
build/
"""


def _requirements_py() -> str:
    return '''from __future__ import annotations

import json
from importlib.resources import files
from typing import Any


def load_requirements() -> list[dict[str, Any]]:
    data = files("plantspeak.data").joinpath("requirements.json").read_text(encoding="utf-8")
    return json.loads(data)


def load_issue_links() -> list[dict[str, Any]]:
    data = files("plantspeak.data").joinpath("issue_links.json").read_text(encoding="utf-8")
    return json.loads(data)


def requirement_ids() -> set[str]:
    return {str(requirement["id"]) for requirement in load_requirements()}
'''


def _pins_py() -> str:
    return '''from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class PinAssignment:
    signal: str
    pin: str
    requirement_id: str
    available_on_dev_board: bool
    notes: str = ""


PIN_ASSIGNMENTS: tuple[PinAssignment, ...] = (
    PinAssignment("red_user_led", "P0_5", "SW-002", False, "Use dev-board LED for early testing."),
    PinAssignment("green_user_led", "P0_11", "SW-002", False, "Use dev-board LED for early testing."),
    PinAssignment("user_push_button", "P0_10", "SW-003", False, "Wake-from-sleep testing needs target hardware."),
    PinAssignment("en_peripherals", "P0_6", "SW-004", False, "Not available on dev board."),
    PinAssignment("i2c_scl", "P0_8", "SW-005", False, "External I2C devices are represented by canned data in dev mode."),
    PinAssignment("i2c_sda", "P0_9", "SW-005", False, "External I2C devices are represented by canned data in dev mode."),
)


def pin_map() -> dict[str, PinAssignment]:
    return {assignment.signal: assignment for assignment in PIN_ASSIGNMENTS}
'''


def _devices_py() -> str:
    return '''from __future__ import annotations

from dataclasses import asdict, dataclass


@dataclass(frozen=True)
class DevBoardProfile:
    name: str
    has_user_leds: bool
    has_user_button: bool
    has_en_peripherals: bool
    has_external_i2c: bool
    transport: str


@dataclass(frozen=True)
class SensorSnapshot:
    photodiode_current_ua: float
    ppfd_umol_m2_s: float
    leaf_temperature_c: float
    ambient_temperature_c: float
    relative_humidity_percent: float
    acceleration_g: tuple[float, float, float]
    source: str

    def to_dict(self) -> dict[str, object]:
        data = asdict(self)
        data["acceleration_g"] = list(self.acceleration_g)
        return data


def default_dev_board_profile() -> DevBoardProfile:
    return DevBoardProfile(
        name="DA14531 development board",
        has_user_leds=False,
        has_user_button=False,
        has_en_peripherals=False,
        has_external_i2c=False,
        transport="ble",
    )


def collect_dev_mode_snapshot(profile: DevBoardProfile | None = None) -> SensorSnapshot:
    selected = profile or default_dev_board_profile()
    source = "canned-dev-mode-data" if not selected.has_external_i2c else "i2c"
    return SensorSnapshot(
        photodiode_current_ua=12.5,
        ppfd_umol_m2_s=245.0,
        leaf_temperature_c=24.2,
        ambient_temperature_c=23.6,
        relative_humidity_percent=51.0,
        acceleration_g=(0.01, -0.02, 1.0),
        source=source,
    )


def build_capability_map(profile: DevBoardProfile | None = None) -> dict[str, str]:
    selected = profile or default_dev_board_profile()
    unavailable = "dev-board-unavailable"
    return {
        "SW-001": "modeled",
        "SW-002": "dev-board-led-substitute" if not selected.has_user_leds else "hardware",
        "SW-003": unavailable if not selected.has_user_button else "hardware",
        "SW-004": unavailable if not selected.has_en_peripherals else "hardware",
        "SW-005": unavailable if not selected.has_external_i2c else "hardware",
        "SW-006": "canned-data" if not selected.has_external_i2c else "hardware",
        "SW-007": "canned-data" if not selected.has_external_i2c else "hardware",
        "SW-008": "canned-data" if not selected.has_external_i2c else "hardware",
        "SW-009": "canned-data" if not selected.has_external_i2c else "hardware",
        "SW-010": "canned-data" if not selected.has_external_i2c else "hardware",
        "SW-011": "dev-board-led-substitute",
        "SW-012": unavailable,
        "SW-013": "canned-data",
        "SW-014": unavailable,
    }
'''


def _icd_py() -> str:
    return '''from __future__ import annotations

from dataclasses import asdict, dataclass

from plantspeak.devices import build_capability_map


@dataclass(frozen=True)
class ICDCapability:
    requirement_id: str
    command: str
    implementation_status: str
    verification_method: str

    def to_dict(self) -> dict[str, str]:
        return asdict(self)


COMMANDS_BY_REQUIREMENT = {
    "SW-001": "describe-icd",
    "SW-002": "set-user-led",
    "SW-003": "read-user-button",
    "SW-004": "set-peripheral-enable",
    "SW-005": "scan-i2c-bus",
    "SW-006": "read-light-sensors",
    "SW-007": "drive-wavelength-leds",
    "SW-008": "read-leaf-temperature",
    "SW-009": "read-ambient-climate",
    "SW-010": "read-acceleration",
    "SW-011": "set-dev-board-led",
    "SW-012": "report-peripheral-enable-unavailable",
    "SW-013": "read-canned-sensor-data",
    "SW-014": "report-user-button-unavailable",
}


def build_icd_capabilities() -> list[ICDCapability]:
    capability_map = build_capability_map()
    capabilities: list[ICDCapability] = []
    for requirement_id, command in COMMANDS_BY_REQUIREMENT.items():
        status = capability_map[requirement_id]
        method = "unit-test-and-dev-mode-cli"
        if status == "dev-board-unavailable":
            method = "requirements-trace-and-target-hardware-deferred-test"
        capabilities.append(ICDCapability(requirement_id, command, status, method))
    return capabilities


def capability_summary() -> dict[str, dict[str, str]]:
    return {capability.requirement_id: capability.to_dict() for capability in build_icd_capabilities()}
'''


def _cli_py() -> str:
    return '''from __future__ import annotations

import argparse
import json

from plantspeak.devices import build_capability_map, collect_dev_mode_snapshot, default_dev_board_profile
from plantspeak.icd import build_icd_capabilities, capability_summary
from plantspeak.requirements import load_issue_links, load_requirements


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="PlantSpeak dev-mode ICD harness.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("list-requirements", help="List implemented software requirements.")
    subparsers.add_parser("trace", help="Print requirement-to-issue and verification trace.")
    subparsers.add_parser("capabilities", help="Print ICD capability summary as JSON.")
    measure = subparsers.add_parser("measure", help="Collect a sensor snapshot.")
    measure.add_argument("--dev-mode", action="store_true", help="Use canned data for unavailable external I2C devices.")
    self_test = subparsers.add_parser("self-test", help="Run deterministic dev-board checks.")
    self_test.add_argument("--dev-mode", action="store_true", help="Use dev-board profile and canned data.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.command == "list-requirements":
        for requirement in load_requirements():
            print(f"{requirement['id']}: {requirement['statement']}")
        return 0
    if args.command == "trace":
        issues = {issue["requirement_ids"][0]: issue for issue in load_issue_links()}
        for capability in build_icd_capabilities():
            issue = issues.get(capability.requirement_id, {})
            print(
                f"{capability.requirement_id} -> #{issue.get('number', 'local')} -> "
                f"{capability.command} -> {capability.verification_method}"
            )
        return 0
    if args.command == "capabilities":
        print(json.dumps(capability_summary(), indent=2, sort_keys=True))
        return 0
    if args.command == "measure":
        if not args.dev_mode:
            raise SystemExit("hardware mode is not implemented yet; rerun with --dev-mode")
        print(json.dumps(collect_dev_mode_snapshot().to_dict(), indent=2, sort_keys=True))
        return 0
    if args.command == "self-test":
        if not args.dev_mode:
            raise SystemExit("self-test currently requires --dev-mode")
        profile = default_dev_board_profile()
        capability_map = build_capability_map(profile)
        checks = {
            "external_i2c_uses_canned_data": capability_map["SW-013"] == "canned-data",
            "button_wake_deferred": capability_map["SW-014"] == "dev-board-unavailable",
            "icd_capabilities_present": len(build_icd_capabilities()) == len(load_requirements()),
        }
        print(json.dumps(checks, indent=2, sort_keys=True))
        return 0 if all(checks.values()) else 1
    raise ValueError(f"unsupported command: {args.command}")


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _test_requirements_py() -> str:
    return '''from plantspeak.requirements import load_issue_links, load_requirements, requirement_ids


def test_requirements_and_issues_are_packaged() -> None:
    requirements = load_requirements()
    issues = load_issue_links()
    assert len(requirements) == 14
    assert len(issues) == 14
    assert "SW-001" in requirement_ids()
    assert "SW-014" in requirement_ids()
    assert all(requirement["acceptance_criteria"] for requirement in requirements)
'''


def _test_devices_py() -> str:
    return '''from plantspeak.devices import build_capability_map, collect_dev_mode_snapshot, default_dev_board_profile
from plantspeak.pins import pin_map


def test_dev_board_profile_tracks_unavailable_hardware() -> None:
    profile = default_dev_board_profile()
    assert not profile.has_external_i2c
    assert not profile.has_user_button
    assert profile.transport == "ble"


def test_pin_assignments_match_requirements() -> None:
    pins = pin_map()
    assert pins["red_user_led"].pin == "P0_5"
    assert pins["green_user_led"].pin == "P0_11"
    assert pins["user_push_button"].pin == "P0_10"
    assert pins["en_peripherals"].pin == "P0_6"
    assert pins["i2c_scl"].pin == "P0_8"
    assert pins["i2c_sda"].pin == "P0_9"


def test_canned_sensor_snapshot_supports_dev_mode() -> None:
    snapshot = collect_dev_mode_snapshot()
    assert snapshot.source == "canned-dev-mode-data"
    assert snapshot.ppfd_umol_m2_s > 0
    assert snapshot.to_dict()["acceleration_g"] == [0.01, -0.02, 1.0]


def test_capability_map_marks_deferred_hardware() -> None:
    capabilities = build_capability_map()
    assert capabilities["SW-006"] == "canned-data"
    assert capabilities["SW-013"] == "canned-data"
    assert capabilities["SW-014"] == "dev-board-unavailable"
'''


def _test_icd_py() -> str:
    return '''from plantspeak.icd import build_icd_capabilities, capability_summary


def test_icd_capabilities_cover_all_software_requirements() -> None:
    capabilities = build_icd_capabilities()
    assert len(capabilities) == 14
    assert {capability.requirement_id for capability in capabilities} == {f"SW-{index:03d}" for index in range(1, 15)}


def test_icd_summary_identifies_deferred_wake_behavior() -> None:
    summary = capability_summary()
    assert summary["SW-014"]["command"] == "report-user-button-unavailable"
    assert summary["SW-014"]["implementation_status"] == "dev-board-unavailable"
'''


def _test_cli_py() -> str:
    return '''import json

import pytest

from plantspeak.cli import main


def test_capabilities_command_outputs_json(capsys) -> None:
    assert main(["capabilities"]) == 0
    output = json.loads(capsys.readouterr().out)
    assert output["SW-001"]["command"] == "describe-icd"


def test_measure_requires_dev_mode() -> None:
    with pytest.raises(SystemExit):
        main(["measure"])


def test_measure_dev_mode_outputs_canned_snapshot(capsys) -> None:
    assert main(["measure", "--dev-mode"]) == 0
    output = json.loads(capsys.readouterr().out)
    assert output["source"] == "canned-dev-mode-data"


def test_self_test_passes_in_dev_mode(capsys) -> None:
    assert main(["self-test", "--dev-mode"]) == 0
    output = json.loads(capsys.readouterr().out)
    assert all(output.values())
'''
