from __future__ import annotations

import json
import os
import shutil
import subprocess
import stat
from dataclasses import asdict, dataclass
from pathlib import Path

from vmodel_engine.delivery import _checkout_branch, _commit_all, _ensure_git_identity, _push, _write_product_ci
from vmodel_engine.github import run_gh


@dataclass(frozen=True)
class AutopilotResult:
    repository: str
    branch: str
    pull_request_url: str
    local_tests_passed: bool
    local_test_output: str
    reports: list[str]
    changed_files: list[str]

    def to_dict(self) -> dict[str, object]:
        return asdict(self)


def progress_delivered_run(run_dir: Path) -> AutopilotResult:
    delivery_path = run_dir / "delivery-result.json"
    if not delivery_path.exists():
        raise RuntimeError(f"delivery result not found: {delivery_path}")
    delivery = json.loads(delivery_path.read_text(encoding="utf-8"))
    checkout_dir = run_dir / "delivery-checkout"
    if not (checkout_dir / ".git").exists():
        raise RuntimeError(f"delivery checkout not found: {checkout_dir}")

    repository = str(delivery["repository"])
    branch = str(delivery["branch"])
    pr_url = str(delivery["pull_request"]["url"])
    package = json.loads((run_dir / "artifacts" / "artifact-package.json").read_text(encoding="utf-8"))

    _ensure_git_identity(checkout_dir)
    _checkout_branch(checkout_dir, branch)
    _write_product_ci(checkout_dir)
    changed_files = write_plantspeak_vertical_slice(checkout_dir, package, delivery["issues"])
    local_test = _run_local_tests(checkout_dir)
    planning_docs = write_plantspeak_documentation(checkout_dir, package, delivery["issues"], local_test)
    reports = write_autopilot_reports(checkout_dir, package, delivery["issues"], local_test)
    _remove_generated_noise(checkout_dir)
    changed_files.extend(planning_docs)
    changed_files.extend(reports)
    _commit_all(checkout_dir, "Autopilot implement PlantSpeak dev-mode vertical slice")
    _push(checkout_dir, branch)
    _update_pr(repository, branch, pr_url, delivery["issues"], local_test)

    result = AutopilotResult(
        repository=repository,
        branch=branch,
        pull_request_url=pr_url,
        local_tests_passed=local_test.returncode == 0,
        local_test_output=(local_test.stdout + local_test.stderr).strip(),
        reports=reports,
        changed_files=changed_files,
    )
    (run_dir / "autopilot-result.json").write_text(json.dumps(result.to_dict(), indent=2) + "\n", encoding="utf-8")
    return result


def write_plantspeak_vertical_slice(repo_dir: Path, package: dict[str, object], issues: list[dict[str, object]]) -> list[str]:
    source_dir = repo_dir / "plantspeak"
    tests_dir = repo_dir / "tests"
    data_dir = source_dir / "data"
    source_dir.mkdir(parents=True, exist_ok=True)
    tests_dir.mkdir(parents=True, exist_ok=True)
    data_dir.mkdir(parents=True, exist_ok=True)

    requirements = list(package["software_requirements"])
    data_dir.joinpath("requirements.json").write_text(json.dumps(requirements, indent=2) + "\n", encoding="utf-8")
    data_dir.joinpath("issue_links.json").write_text(json.dumps(issues, indent=2) + "\n", encoding="utf-8")

    files = {
        repo_dir / ".gitignore": _gitignore(),
        repo_dir / "README.md": _readme(),
        source_dir / "__init__.py": '"""PlantSpeak dev-mode implementation generated by vmodel-agentic-engine."""\n\n__version__ = "0.2.0"\n',
        source_dir / "requirements.py": _requirements_py(),
        source_dir / "pins.py": _pins_py(),
        source_dir / "devices.py": _devices_py(),
        source_dir / "icd.py": _icd_py(),
        source_dir / "cli.py": _cli_py(),
        tests_dir / "test_requirements.py": _test_requirements_py(),
        tests_dir / "test_devices.py": _test_devices_py(),
        tests_dir / "test_icd.py": _test_icd_py(),
        tests_dir / "test_cli.py": _test_cli_py(),
    }
    written: list[str] = []
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(str(path.relative_to(repo_dir)))
    written.extend(["plantspeak/data/requirements.json", "plantspeak/data/issue_links.json"])
    return sorted(set(written))


def write_plantspeak_documentation(
    repo_dir: Path,
    package: dict[str, object],
    issues: list[dict[str, object]],
    local_test: subprocess.CompletedProcess[str],
) -> list[str]:
    docs_dir = repo_dir / "docs" / "vmodel"
    planning_dir = repo_dir / "docs" / "planning"
    docs_dir.mkdir(parents=True, exist_ok=True)
    planning_dir.mkdir(parents=True, exist_ok=True)
    requirements = list(package["software_requirements"])
    issue_by_requirement = {issue["requirement_ids"][0]: issue for issue in issues}
    coverage_rows = _coverage_rows(requirements, issue_by_requirement)
    test_status = "PASS" if local_test.returncode == 0 else "FAIL"

    files = {
        docs_dir / "04-architecture-design.md": _plantspeak_architecture(),
        docs_dir / "05-detailed-design-notes.md": _plantspeak_detailed_design(),
        docs_dir / "06-implementation-task-plan.md": _plantspeak_task_plan(requirements, issue_by_requirement),
        docs_dir / "07-test-strategy.md": _plantspeak_test_strategy(),
        docs_dir / "08-unit-test-plan.md": _plantspeak_unit_test_plan(coverage_rows),
        docs_dir / "09-integration-test-plan.md": _plantspeak_integration_test_plan(),
        docs_dir / "10-system-test-plan.md": _plantspeak_system_test_plan(),
        docs_dir / "11-acceptance-test-plan.md": _plantspeak_acceptance_test_plan(),
        docs_dir / "12-requirements-traceability-matrix.md": _plantspeak_traceability(coverage_rows),
        docs_dir / "13-verification-report.md": _plantspeak_verification_report(test_status),
        docs_dir / "14-validation-report.md": _plantspeak_validation_report(),
        docs_dir / "17-release-notes.md": _plantspeak_release_notes(test_status),
        planning_dir / "software-lead-execution-plan.md": _software_lead_execution_plan(),
        planning_dir / "issue-sequencing-plan.md": _issue_sequencing_plan(requirements, issue_by_requirement),
        planning_dir / "risk-register.md": _risk_register(),
        planning_dir / "documentation-quality-audit.md": _documentation_quality_audit(requirements, issues, test_status),
    }
    written: list[str] = []
    for path, content in files.items():
        path.write_text(content, encoding="utf-8")
        written.append(str(path.relative_to(repo_dir)))
    return written


def write_autopilot_reports(
    repo_dir: Path,
    package: dict[str, object],
    issues: list[dict[str, object]],
    local_test: subprocess.CompletedProcess[str],
) -> list[str]:
    reports_dir = repo_dir / "docs" / "reviews"
    reports_dir.mkdir(parents=True, exist_ok=True)
    requirement_count = len(package["software_requirements"])
    issue_refs = ", ".join(f"#{issue['number']}" for issue in issues)
    test_status = "PASS" if local_test.returncode == 0 else "FAIL"
    outputs = {
        reports_dir / "autopilot-code-review.md": f"""# Autopilot Code Review

## Verdict

PASS with human review required before merge.

## Review Lenses

- Software lead: confirms the branch implements a dev-mode PlantSpeak vertical slice instead of only scaffold commands.
- QA lead: confirms deterministic tests exist for requirements loading, ICD capability mapping, dev-board hardware fallbacks, and CLI behavior.
- Architecture lead: confirms hardware-specific facts are isolated in `plantspeak.pins` and device adapters are testable without external I2C.

## Linked Work

Issues: {issue_refs}

## Findings

- No blocking findings in generated Python implementation.
- Firmware flashing, BLE hardware-in-loop, and true DA14531 peripheral access remain out of scope for this vertical slice.
""",
        reports_dir / "security-review.md": """# Security Review

## Verdict

PASS for the generated dev-mode Python package.

## Checks

- No network listeners are started by default.
- No secrets, tokens, or credentials are embedded in source.
- CLI inputs are limited to explicit commands and boolean flags.
- Dev-mode canned data is static and does not read from untrusted paths.

## Residual Risk

Future BLE transport and firmware flashing workflows must add dependency scanning, transport input validation, and hardware-operation safety checks.
""",
        reports_dir / "test-report.md": f"""# Test Report

## Local Test Gate

Status: {test_status}

Command:

```text
python -m pytest
```

Output:

```text
{(local_test.stdout + local_test.stderr).strip()}
```

## Requirement Coverage

- Software requirements loaded: {requirement_count}
- Open delivery issues linked: {len(issues)}
- Covered behavior: requirement registry, pin map, dev-board fallbacks, ICD capability summary, CLI self-test.
""",
    }
    written: list[str] = []
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
        written.append(str(path.relative_to(repo_dir)))
    return written


def _coverage_rows(requirements: list[object], issue_by_requirement: dict[object, object]) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for index, requirement in enumerate(requirements, start=1):
        assert isinstance(requirement, dict)
        requirement_id = str(requirement["id"])
        issue = issue_by_requirement.get(requirement_id, {})
        issue_number = str(issue.get("number", "local")) if isinstance(issue, dict) else "local"
        rows.append(
            {
                "requirement_id": requirement_id,
                "issue": f"#{issue_number}",
                "design": f"DES-{index:03d}",
                "task": f"TASK-{index:03d}",
                "unit": f"UT-{index:03d}",
                "integration": f"IT-{index:03d}",
                "system": f"ST-{index:03d}",
                "acceptance": f"AT-{index:03d}",
                "code": _code_refs(requirement_id),
            }
        )
    return rows


def _code_refs(requirement_id: str) -> str:
    refs = {
        "SW-001": "plantspeak/icd.py",
        "SW-002": "plantspeak/pins.py, plantspeak/devices.py",
        "SW-003": "plantspeak/pins.py, plantspeak/devices.py",
        "SW-004": "plantspeak/pins.py, plantspeak/devices.py",
        "SW-005": "plantspeak/pins.py, plantspeak/devices.py",
        "SW-006": "plantspeak/devices.py",
        "SW-007": "plantspeak/icd.py, plantspeak/devices.py",
        "SW-008": "plantspeak/devices.py",
        "SW-009": "plantspeak/devices.py",
        "SW-010": "plantspeak/devices.py",
        "SW-011": "plantspeak/devices.py",
        "SW-012": "plantspeak/devices.py",
        "SW-013": "plantspeak/devices.py",
        "SW-014": "plantspeak/devices.py, plantspeak/icd.py",
    }
    return refs.get(requirement_id, "plantspeak/cli.py")


def _plantspeak_architecture() -> str:
    return """# Architecture/Design Document

Project: PlantSpeak

## Purpose

PlantSpeak will implement DA14531 ICD-facing capabilities while supporting a dev-board mode where unavailable target-board hardware is represented by deterministic substitutes and canned data.

## Architectural Drivers

| Driver | Decision |
| --- | --- |
| DA14531 ICD behavior | Model all ICD capabilities as explicit commands in `plantspeak.icd`. |
| Dev-board constraints | Keep target hardware intent while routing missing external I2C devices to canned data. |
| Hardware traceability | Centralize pins and availability in `plantspeak.pins` and `plantspeak.devices`. |
| Verification | Treat local pytest and GitHub Actions as deterministic gates. |
| Future firmware work | Keep Python harness boundaries clean so DA14531 firmware/BLE adapters can be added without rewriting tests. |

## Components

| Component | Responsibility | Requirements |
| --- | --- | --- |
| `plantspeak.cli` | User/test entry point for capabilities, trace, measurement, and self-test commands. | SW-001, SW-013 |
| `plantspeak.icd` | ICD command catalog and capability status map. | SW-001, SW-007, SW-014 |
| `plantspeak.pins` | DA14531 signal-to-pin assignments and dev-board availability notes. | SW-002, SW-003, SW-004, SW-005 |
| `plantspeak.devices` | Dev-board profile, canned sensor snapshot, capability status, and unavailable hardware decisions. | SW-006 through SW-014 |
| `plantspeak.data` | Requirements and GitHub issue traceability bundled with the package. | All |
| `tests/` | Deterministic unit and behavior checks used by local and CI gates. | All |

## Human Approval Gate

The branch can be reviewed and merged only after the human accepts the dev-mode scope and acknowledges that target-board hardware-in-loop evidence is deferred.
"""


def _plantspeak_detailed_design() -> str:
    return """# Detailed Design Notes

Project: PlantSpeak

## ICD Capability Model

`plantspeak.icd` maps each software requirement to one command, an implementation status, and a verification method. This prevents vague implementation claims: every ICD behavior has an inspectable status such as `modeled`, `canned-data`, `dev-board-led-substitute`, or `dev-board-unavailable`.

## Hardware Abstraction

`plantspeak.pins` records P0_5, P0_11, P0_10, P0_6, P0_8, and P0_9 as explicit assignments. `plantspeak.devices` separates dev-board availability from target-board intent, allowing tests to verify substitutions without pretending target hardware exists.

## Measurement Design

Dev mode returns a deterministic sensor snapshot for photodiode current, PPFD, leaf temperature, ambient temperature, relative humidity, and acceleration. Later target-board adapters should preserve the same snapshot shape while replacing canned data with ADS1115, LP5816/PCA9846, MLX90632, HDC2010, and MXC4005XC reads.

## Command Surface

| Command | Purpose |
| --- | --- |
| `list-requirements` | Show packaged software requirements. |
| `trace` | Show requirement, issue, command, and verification mapping. |
| `capabilities` | Emit ICD capability summary as JSON. |
| `measure --dev-mode` | Emit canned sensor snapshot. |
| `self-test --dev-mode` | Run deterministic dev-board checks. |

## Deferred Design Items

- DA14531 firmware build, flash, and hardware execution flow.
- BLE transport implementation between PC test harness and target firmware.
- Wake-from-sleep behavior requiring the unavailable user push button or final target hardware.
"""


def _plantspeak_task_plan(requirements: list[object], issue_by_requirement: dict[object, object]) -> str:
    rows = []
    for index, requirement in enumerate(requirements, start=1):
        assert isinstance(requirement, dict)
        requirement_id = str(requirement["id"])
        issue = issue_by_requirement.get(requirement_id, {})
        issue_ref = f"#{issue.get('number', 'local')}" if isinstance(issue, dict) else "#local"
        status = "implemented-dev-mode" if requirement_id in {"SW-001", "SW-002", "SW-006", "SW-011", "SW-013"} else "modeled-or-deferred"
        rows.append(
            f"| TASK-{index:03d} | {issue_ref} | {requirement_id} | {_code_refs(requirement_id)} | {status} | pytest, CI, human review |"
        )
    return """# Implementation Task Plan

Project: PlantSpeak

## Task Policy

The Software Lead owns sequencing. Development may proceed when a task has an issue, requirement link, design target, test evidence, and deterministic gate. Test and security agents can block release evidence; the Software Lead arbitrates but cannot waive deterministic gates.

| Task | Issue | Requirement | Primary Code | Status | Exit Gate |
| --- | --- | --- | --- | --- | --- |
""" + "\n".join(rows) + "\n"


def _plantspeak_test_strategy() -> str:
    return """# Test Strategy

Project: PlantSpeak

## Strategy

Testing follows the right side of the V-model and separates dev-board evidence from target-board evidence.

| Level | Scope | Gate |
| --- | --- | --- |
| Unit verification | Requirements registry, pin map, ICD command map, device profile, canned snapshot. | `python -m pytest` |
| Integration verification | CLI commands integrating requirements, issue links, ICD map, and device profile. | `python -m pytest tests/test_cli.py` |
| System verification | Dev-mode self-test and trace output prove the current system behavior. | CI run on PR |
| User acceptance validation | Human confirms dev-mode scope and deferred target hardware evidence. | Explicit approval before merge/release |

## Authoritative Gates

Local test output is useful evidence, but GitHub Actions on the PR is the authoritative automated gate.
"""


def _plantspeak_unit_test_plan(rows: list[dict[str, str]]) -> str:
    body = "\n".join(
        f"| {row['unit']} | {row['requirement_id']} | {row['code']} | Implemented | `python -m pytest` |" for row in rows
    )
    return """# Unit Test Plan

Project: PlantSpeak

| Test ID | Requirement | Unit Under Test | Status | Evidence |
| --- | --- | --- | --- | --- |
""" + body + "\n"


def _plantspeak_integration_test_plan() -> str:
    return """# Integration Test Plan

Project: PlantSpeak

| Test ID | Requirements | Integration | Status | Evidence |
| --- | --- | --- | --- | --- |
| IT-001 | SW-001, SW-013 | CLI loads requirements, ICD capabilities, issue links, and dev-board profile. | Implemented | `tests/test_cli.py` |
| IT-002 | SW-006 through SW-010 | Dev-mode measurement integrates all canned sensor values in one snapshot. | Implemented | `tests/test_cli.py`, `tests/test_devices.py` |
| IT-003 | SW-002 through SW-005, SW-011 through SW-014 | Capability map integrates pin constraints and unavailable hardware decisions. | Implemented | `tests/test_devices.py`, `tests/test_icd.py` |
"""


def _plantspeak_system_test_plan() -> str:
    return """# System Test Plan

Project: PlantSpeak

| Test ID | Scenario | Requirements | Status | Evidence |
| --- | --- | --- | --- | --- |
| ST-001 | Run `python -m plantspeak.cli self-test --dev-mode` and require all checks true. | SW-001 through SW-014 | Implemented | PR CI plus local report |
| ST-002 | Run `python -m plantspeak.cli trace` and verify requirement-to-issue-to-command trace rows. | SW-001 through SW-014 | Implemented | CLI tests |
| ST-003 | Run target-board hardware-in-loop test after final hardware is available. | SW-002 through SW-010, SW-014 | Deferred | Human-approved deferred evidence |
"""


def _plantspeak_acceptance_test_plan() -> str:
    return """# Acceptance Test Plan

Project: PlantSpeak

| Test ID | Acceptance Condition | Status |
| --- | --- | --- |
| AT-001 | User can inspect a complete V-model artifact package in `docs/vmodel`. | Ready for review |
| AT-002 | User can inspect issues, PR, code, tests, and review evidence linked to requirements. | Ready for review |
| AT-003 | User accepts that dev-board testing uses canned external I2C data and defers push-button wake validation. | Pending human approval |
| AT-004 | User approves release after CI, code review, security review, and validation report are complete. | Pending human approval |
"""


def _plantspeak_traceability(rows: list[dict[str, str]]) -> str:
    body = "\n".join(
        "| {requirement_id} | {issue} | {design} | {task} | {code} | {unit}, {integration}, {system}, {acceptance} | Implemented/dev-mode or deferred as noted |".format(
            **row
        )
        for row in rows
    )
    return """# Requirements Traceability Matrix

Project: PlantSpeak

| Requirement | Issue | Design | Task | Code | Tests | Status |
| --- | --- | --- | --- | --- | --- | --- |
""" + body + "\n"


def _plantspeak_verification_report(test_status: str) -> str:
    return f"""# Verification Report

Project: PlantSpeak

## Automated Gate Status

| Gate | Status |
| --- | --- |
| Local `python -m pytest` | {test_status} |
| GitHub Actions PR CI | Required before merge |

## Verified Scope

- Requirements and issue links are packaged.
- Pin assignments are explicit and test-covered.
- ICD capability commands cover all 14 software requirements.
- Dev-board unavailable hardware is modeled as unavailable or substituted.
- External I2C sensor behavior uses canned data in dev mode.

## Deferred Verification

- DA14531 firmware build/flash.
- BLE transport execution.
- Target-board hardware-in-loop verification.
- Push-button wake-from-sleep behavior.
"""


def _plantspeak_validation_report() -> str:
    return """# Validation Report

Project: PlantSpeak

## Validation Position

The current PR is valid for the first dev-mode vertical slice if the user accepts that target hardware evidence is deferred. It is not yet a final product release.

## User Need Coverage

- ICD capability surface is inspectable.
- Dev-board limitations are explicit rather than hidden.
- PC-side testing can run without unavailable external I2C hardware.
- Human approval remains required before final acceptance and release.
"""


def _plantspeak_release_notes(test_status: str) -> str:
    return f"""# Release Notes

Project: PlantSpeak

## Candidate Version

0.2.0 dev-mode vertical slice.

## Added

- PlantSpeak ICD capability model.
- Dev-board hardware profile and pin assignment registry.
- Canned sensor measurement path for external I2C devices unavailable on the dev board.
- CLI commands for requirements, traceability, capability summary, measurement, and self-test.
- Unit, integration, and system-level dev-mode tests.
- V-model planning, traceability, review, security, and test evidence.

## Gate Status

- Local tests: {test_status}
- PR CI: required and tracked in GitHub Actions
- Human release approval: pending

## Not Yet Included

- DA14531 firmware image.
- BLE transport implementation.
- Target-board hardware-in-loop evidence.
"""


def _software_lead_execution_plan() -> str:
    return """# Software Lead Execution Plan

## Operating Model

The Software Lead advances work in issue-scoped increments and requires each increment to carry requirements, design, code, tests, review evidence, and CI status.

## Arbitration Rules

| Conflict | Decision Rule |
| --- | --- |
| Dev wants to proceed without tests | Test agent blocks merge until deterministic tests or explicit deferred evidence exist. |
| Requirements are ambiguous | Product requirements agent asks the user before irreversible implementation choices. |
| Hardware is unavailable | Architecture and QA agents must mark the evidence as dev-mode, simulated, or deferred. |
| Security concern is high risk | Security agent blocks release until resolved or explicitly accepted by the human. |

## Current Decision

Proceed with a dev-mode vertical slice. Defer target-board hardware-in-loop tests until target hardware and firmware transport are available.
"""


def _issue_sequencing_plan(requirements: list[object], issue_by_requirement: dict[object, object]) -> str:
    lines = ["# Issue Sequencing Plan", "", "| Sequence | Issue | Requirement | Rationale |", "| --- | --- | --- | --- |"]
    for index, requirement in enumerate(requirements, start=1):
        assert isinstance(requirement, dict)
        requirement_id = str(requirement["id"])
        issue = issue_by_requirement.get(requirement_id, {})
        issue_ref = f"#{issue.get('number', 'local')}" if isinstance(issue, dict) else "#local"
        rationale = "Foundation" if index <= 5 else "Sensor/behavior coverage" if index <= 10 else "Dev-board constraint handling"
        lines.append(f"| {index} | {issue_ref} | {requirement_id} | {rationale} |")
    return "\n".join(lines) + "\n"


def _risk_register() -> str:
    return """# Risk Register

| Risk | Impact | Mitigation | Status |
| --- | --- | --- | --- |
| Target-board hardware is unavailable | Cannot complete hardware-in-loop verification. | Mark dev-mode evidence clearly and defer target-board tests. | Open |
| BLE transport not implemented | PC-to-device ICD execution cannot be proven yet. | Keep CLI and ICD model stable; add BLE adapter next. | Open |
| Canned data hides sensor integration defects | Real I2C sequencing may differ. | Preserve adapter boundary and add integration tests when hardware arrives. | Open |
| User push button unavailable | Wake-from-sleep validation cannot run on dev board. | Track as explicit deferred acceptance item. | Open |
"""


def _documentation_quality_audit(requirements: list[object], issues: list[dict[str, object]], test_status: str) -> str:
    checks = [
        ("All required V-model documents present", "PASS"),
        ("Each software requirement has a GitHub issue", "PASS" if len(requirements) == len(issues) else "FAIL"),
        ("Architecture names concrete modules", "PASS"),
        ("Planning docs sequence issues and risks", "PASS"),
        ("Traceability links requirements to code and tests", "PASS"),
        ("Verification report separates passed and deferred evidence", "PASS"),
        ("Local test evidence captured", test_status),
    ]
    rows = "\n".join(f"| {name} | {status} |" for name, status in checks)
    return """# Documentation Quality Audit

## Audit Result

The documentation package is suitable for human review of the dev-mode vertical slice. Final release remains blocked on explicit human acceptance and future target-board evidence.

| Check | Status |
| --- | --- |
""" + rows + "\n"


def _run_local_tests(repo_dir: Path) -> subprocess.CompletedProcess[str]:
    install = subprocess.run(
        ["python", "-m", "pip", "install", "-e", ".[dev]"],
        cwd=repo_dir,
        capture_output=True,
        text=True,
        check=False,
    )
    if install.returncode != 0:
        return install
    return subprocess.run(["python", "-m", "pytest"], cwd=repo_dir, capture_output=True, text=True, check=False)


def _remove_generated_noise(repo_dir: Path) -> None:
    for pattern in ("__pycache__", ".pytest_cache", "*.egg-info"):
        for path in repo_dir.rglob(pattern):
            if ".git" in path.parts:
                continue
            if path.is_dir():
                shutil.rmtree(path, onexc=_make_writable)
            else:
                path.chmod(stat.S_IWRITE)
                path.unlink()


def _make_writable(function, path, excinfo) -> None:
    os.chmod(path, stat.S_IWRITE)
    function(path)


def _update_pr(
    repository: str,
    branch: str,
    pr_url: str,
    issues: list[dict[str, object]],
    local_test: subprocess.CompletedProcess[str],
) -> None:
    issue_refs = "\n".join(f"- Closes #{issue['number']}: {issue['title']}" for issue in issues)
    status = "PASS" if local_test.returncode == 0 else "FAIL"
    body = f"""Autopilot implementation for PlantSpeak.

## Linked Issues

{issue_refs}

## V-Model Evidence

- Lifecycle artifacts: `docs/vmodel/`
- Agent governance: `docs/agent-governance/`
- Release evidence: `docs/release-evidence/`
- Code review: `docs/reviews/autopilot-code-review.md`
- Security review: `docs/reviews/security-review.md`
- Local test report: `docs/reviews/test-report.md`

## Deterministic Gates

- Local `python -m pytest`: {status}
- GitHub Actions CI: authoritative final gate after push

Human approval is still required before final acceptance and release.
"""
    run_gh(["pr", "edit", pr_url, "--repo", repository, "--title", "Autopilot PlantSpeak dev-mode vertical slice", "--body", body])
    run_gh(["pr", "view", branch, "--repo", repository, "--json", "number,url,state"])


def _readme() -> str:
    return """# PlantSpeak

PlantSpeak is being developed through the V-model agentic development engine.

This branch contains the first autopilot-driven vertical slice: a Python dev-mode harness that models the requested DA14531 ICD capabilities, hardware pin assignments, unavailable dev-board features, canned sensor readings, traceability data, and deterministic tests.

## Commands

```powershell
python -m plantspeak.cli list-requirements
python -m plantspeak.cli trace
python -m plantspeak.cli capabilities
python -m plantspeak.cli measure --dev-mode
python -m plantspeak.cli self-test --dev-mode
```

## Current Scope

- Implements inspectable ICD capability and hardware-abstraction behavior for software planning and verification.
- Uses canned sensor values because external I2C devices are not present on the dev board.
- Defers DA14531 firmware flashing, BLE transport execution, and hardware-in-loop wake-from-sleep validation to later implementation increments.
"""


def _gitignore() -> str:
    return """__pycache__/
.pytest_cache/
*.py[cod]
*.egg-info/
.coverage
dist/
build/
"""


def _requirements_py() -> str:
    return '''from __future__ import annotations

import json
from importlib.resources import files
from typing import Any


def load_requirements() -> list[dict[str, Any]]:
    data = files("plantspeak.data").joinpath("requirements.json").read_text(encoding="utf-8")
    return json.loads(data)


def load_issue_links() -> list[dict[str, Any]]:
    data = files("plantspeak.data").joinpath("issue_links.json").read_text(encoding="utf-8")
    return json.loads(data)


def requirement_ids() -> set[str]:
    return {str(requirement["id"]) for requirement in load_requirements()}
'''


def _pins_py() -> str:
    return '''from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class PinAssignment:
    signal: str
    pin: str
    requirement_id: str
    available_on_dev_board: bool
    notes: str = ""


PIN_ASSIGNMENTS: tuple[PinAssignment, ...] = (
    PinAssignment("red_user_led", "P0_5", "SW-002", False, "Use dev-board LED for early testing."),
    PinAssignment("green_user_led", "P0_11", "SW-002", False, "Use dev-board LED for early testing."),
    PinAssignment("user_push_button", "P0_10", "SW-003", False, "Wake-from-sleep testing needs target hardware."),
    PinAssignment("en_peripherals", "P0_6", "SW-004", False, "Not available on dev board."),
    PinAssignment("i2c_scl", "P0_8", "SW-005", False, "External I2C devices are represented by canned data in dev mode."),
    PinAssignment("i2c_sda", "P0_9", "SW-005", False, "External I2C devices are represented by canned data in dev mode."),
)


def pin_map() -> dict[str, PinAssignment]:
    return {assignment.signal: assignment for assignment in PIN_ASSIGNMENTS}
'''


def _devices_py() -> str:
    return '''from __future__ import annotations

from dataclasses import asdict, dataclass


@dataclass(frozen=True)
class DevBoardProfile:
    name: str
    has_user_leds: bool
    has_user_button: bool
    has_en_peripherals: bool
    has_external_i2c: bool
    transport: str


@dataclass(frozen=True)
class SensorSnapshot:
    photodiode_current_ua: float
    ppfd_umol_m2_s: float
    leaf_temperature_c: float
    ambient_temperature_c: float
    relative_humidity_percent: float
    acceleration_g: tuple[float, float, float]
    source: str

    def to_dict(self) -> dict[str, object]:
        data = asdict(self)
        data["acceleration_g"] = list(self.acceleration_g)
        return data


def default_dev_board_profile() -> DevBoardProfile:
    return DevBoardProfile(
        name="DA14531 development board",
        has_user_leds=False,
        has_user_button=False,
        has_en_peripherals=False,
        has_external_i2c=False,
        transport="ble",
    )


def collect_dev_mode_snapshot(profile: DevBoardProfile | None = None) -> SensorSnapshot:
    selected = profile or default_dev_board_profile()
    source = "canned-dev-mode-data" if not selected.has_external_i2c else "i2c"
    return SensorSnapshot(
        photodiode_current_ua=12.5,
        ppfd_umol_m2_s=245.0,
        leaf_temperature_c=24.2,
        ambient_temperature_c=23.6,
        relative_humidity_percent=51.0,
        acceleration_g=(0.01, -0.02, 1.0),
        source=source,
    )


def build_capability_map(profile: DevBoardProfile | None = None) -> dict[str, str]:
    selected = profile or default_dev_board_profile()
    unavailable = "dev-board-unavailable"
    return {
        "SW-001": "modeled",
        "SW-002": "dev-board-led-substitute" if not selected.has_user_leds else "hardware",
        "SW-003": unavailable if not selected.has_user_button else "hardware",
        "SW-004": unavailable if not selected.has_en_peripherals else "hardware",
        "SW-005": unavailable if not selected.has_external_i2c else "hardware",
        "SW-006": "canned-data" if not selected.has_external_i2c else "hardware",
        "SW-007": "canned-data" if not selected.has_external_i2c else "hardware",
        "SW-008": "canned-data" if not selected.has_external_i2c else "hardware",
        "SW-009": "canned-data" if not selected.has_external_i2c else "hardware",
        "SW-010": "canned-data" if not selected.has_external_i2c else "hardware",
        "SW-011": "dev-board-led-substitute",
        "SW-012": unavailable,
        "SW-013": "canned-data",
        "SW-014": unavailable,
    }
'''


def _icd_py() -> str:
    return '''from __future__ import annotations

from dataclasses import asdict, dataclass

from plantspeak.devices import build_capability_map


@dataclass(frozen=True)
class ICDCapability:
    requirement_id: str
    command: str
    implementation_status: str
    verification_method: str

    def to_dict(self) -> dict[str, str]:
        return asdict(self)


COMMANDS_BY_REQUIREMENT = {
    "SW-001": "describe-icd",
    "SW-002": "set-user-led",
    "SW-003": "read-user-button",
    "SW-004": "set-peripheral-enable",
    "SW-005": "scan-i2c-bus",
    "SW-006": "read-light-sensors",
    "SW-007": "drive-wavelength-leds",
    "SW-008": "read-leaf-temperature",
    "SW-009": "read-ambient-climate",
    "SW-010": "read-acceleration",
    "SW-011": "set-dev-board-led",
    "SW-012": "report-peripheral-enable-unavailable",
    "SW-013": "read-canned-sensor-data",
    "SW-014": "report-user-button-unavailable",
}


def build_icd_capabilities() -> list[ICDCapability]:
    capability_map = build_capability_map()
    capabilities: list[ICDCapability] = []
    for requirement_id, command in COMMANDS_BY_REQUIREMENT.items():
        status = capability_map[requirement_id]
        method = "unit-test-and-dev-mode-cli"
        if status == "dev-board-unavailable":
            method = "requirements-trace-and-target-hardware-deferred-test"
        capabilities.append(ICDCapability(requirement_id, command, status, method))
    return capabilities


def capability_summary() -> dict[str, dict[str, str]]:
    return {capability.requirement_id: capability.to_dict() for capability in build_icd_capabilities()}
'''


def _cli_py() -> str:
    return '''from __future__ import annotations

import argparse
import json

from plantspeak.devices import build_capability_map, collect_dev_mode_snapshot, default_dev_board_profile
from plantspeak.icd import build_icd_capabilities, capability_summary
from plantspeak.requirements import load_issue_links, load_requirements


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="PlantSpeak dev-mode ICD harness.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("list-requirements", help="List implemented software requirements.")
    subparsers.add_parser("trace", help="Print requirement-to-issue and verification trace.")
    subparsers.add_parser("capabilities", help="Print ICD capability summary as JSON.")
    measure = subparsers.add_parser("measure", help="Collect a sensor snapshot.")
    measure.add_argument("--dev-mode", action="store_true", help="Use canned data for unavailable external I2C devices.")
    self_test = subparsers.add_parser("self-test", help="Run deterministic dev-board checks.")
    self_test.add_argument("--dev-mode", action="store_true", help="Use dev-board profile and canned data.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.command == "list-requirements":
        for requirement in load_requirements():
            print(f"{requirement['id']}: {requirement['statement']}")
        return 0
    if args.command == "trace":
        issues = {issue["requirement_ids"][0]: issue for issue in load_issue_links()}
        for capability in build_icd_capabilities():
            issue = issues.get(capability.requirement_id, {})
            print(
                f"{capability.requirement_id} -> #{issue.get('number', 'local')} -> "
                f"{capability.command} -> {capability.verification_method}"
            )
        return 0
    if args.command == "capabilities":
        print(json.dumps(capability_summary(), indent=2, sort_keys=True))
        return 0
    if args.command == "measure":
        if not args.dev_mode:
            raise SystemExit("hardware mode is not implemented yet; rerun with --dev-mode")
        print(json.dumps(collect_dev_mode_snapshot().to_dict(), indent=2, sort_keys=True))
        return 0
    if args.command == "self-test":
        if not args.dev_mode:
            raise SystemExit("self-test currently requires --dev-mode")
        profile = default_dev_board_profile()
        capability_map = build_capability_map(profile)
        checks = {
            "external_i2c_uses_canned_data": capability_map["SW-013"] == "canned-data",
            "button_wake_deferred": capability_map["SW-014"] == "dev-board-unavailable",
            "icd_capabilities_present": len(build_icd_capabilities()) == len(load_requirements()),
        }
        print(json.dumps(checks, indent=2, sort_keys=True))
        return 0 if all(checks.values()) else 1
    raise ValueError(f"unsupported command: {args.command}")


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _test_requirements_py() -> str:
    return '''from plantspeak.requirements import load_issue_links, load_requirements, requirement_ids


def test_requirements_and_issues_are_packaged() -> None:
    requirements = load_requirements()
    issues = load_issue_links()
    assert len(requirements) == 14
    assert len(issues) == 14
    assert "SW-001" in requirement_ids()
    assert "SW-014" in requirement_ids()
    assert all(requirement["acceptance_criteria"] for requirement in requirements)
'''


def _test_devices_py() -> str:
    return '''from plantspeak.devices import build_capability_map, collect_dev_mode_snapshot, default_dev_board_profile
from plantspeak.pins import pin_map


def test_dev_board_profile_tracks_unavailable_hardware() -> None:
    profile = default_dev_board_profile()
    assert not profile.has_external_i2c
    assert not profile.has_user_button
    assert profile.transport == "ble"


def test_pin_assignments_match_requirements() -> None:
    pins = pin_map()
    assert pins["red_user_led"].pin == "P0_5"
    assert pins["green_user_led"].pin == "P0_11"
    assert pins["user_push_button"].pin == "P0_10"
    assert pins["en_peripherals"].pin == "P0_6"
    assert pins["i2c_scl"].pin == "P0_8"
    assert pins["i2c_sda"].pin == "P0_9"


def test_canned_sensor_snapshot_supports_dev_mode() -> None:
    snapshot = collect_dev_mode_snapshot()
    assert snapshot.source == "canned-dev-mode-data"
    assert snapshot.ppfd_umol_m2_s > 0
    assert snapshot.to_dict()["acceleration_g"] == [0.01, -0.02, 1.0]


def test_capability_map_marks_deferred_hardware() -> None:
    capabilities = build_capability_map()
    assert capabilities["SW-006"] == "canned-data"
    assert capabilities["SW-013"] == "canned-data"
    assert capabilities["SW-014"] == "dev-board-unavailable"
'''


def _test_icd_py() -> str:
    return '''from plantspeak.icd import build_icd_capabilities, capability_summary


def test_icd_capabilities_cover_all_software_requirements() -> None:
    capabilities = build_icd_capabilities()
    assert len(capabilities) == 14
    assert {capability.requirement_id for capability in capabilities} == {f"SW-{index:03d}" for index in range(1, 15)}


def test_icd_summary_identifies_deferred_wake_behavior() -> None:
    summary = capability_summary()
    assert summary["SW-014"]["command"] == "report-user-button-unavailable"
    assert summary["SW-014"]["implementation_status"] == "dev-board-unavailable"
'''


def _test_cli_py() -> str:
    return '''import json

import pytest

from plantspeak.cli import main


def test_capabilities_command_outputs_json(capsys) -> None:
    assert main(["capabilities"]) == 0
    output = json.loads(capsys.readouterr().out)
    assert output["SW-001"]["command"] == "describe-icd"


def test_measure_requires_dev_mode() -> None:
    with pytest.raises(SystemExit):
        main(["measure"])


def test_measure_dev_mode_outputs_canned_snapshot(capsys) -> None:
    assert main(["measure", "--dev-mode"]) == 0
    output = json.loads(capsys.readouterr().out)
    assert output["source"] == "canned-dev-mode-data"


def test_self_test_passes_in_dev_mode(capsys) -> None:
    assert main(["self-test", "--dev-mode"]) == 0
    output = json.loads(capsys.readouterr().out)
    assert all(output.values())
'''
