from __future__ import annotations

import json
import re
from pathlib import Path

from vmodel_engine.models import ArtifactPackage


def generate_python_cli_project(package: ArtifactPackage, project_dir: Path) -> list[Path]:
    project_dir.mkdir(parents=True, exist_ok=True)
    package_name = _identifier(package.project_name)
    source_dir = project_dir / package_name
    tests_dir = project_dir / "tests"
    data_dir = source_dir / "data"
    data_dir.mkdir(parents=True, exist_ok=True)
    tests_dir.mkdir(parents=True, exist_ok=True)

    requirement_records = [
        {
            "id": requirement.id,
            "statement": requirement.statement,
            "priority": requirement.priority,
            "acceptance_criteria": requirement.acceptance_criteria,
        }
        for requirement in package.software_requirements
    ]

    files = {
        project_dir / "README.md": _readme(package, package_name),
        project_dir / "pyproject.toml": _pyproject(package, package_name),
        source_dir / "__init__.py": f'"""Generated project for {package.project_name}."""\n\n__version__ = "0.1.0"\n',
        source_dir / "cli.py": _cli_py(package_name),
        data_dir / "requirements.json": json.dumps(requirement_records, indent=2) + "\n",
        tests_dir / "test_cli.py": _test_cli(package_name),
        tests_dir / "test_requirements.py": _test_requirements(package_name, len(requirement_records)),
    }
    written: list[Path] = []
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written


def _identifier(name: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9]+", "_", name.strip().lower()).strip("_")
    if not cleaned:
        return "generated_app"
    if cleaned[0].isdigit():
        return f"app_{cleaned}"
    return cleaned


def _readme(package: ArtifactPackage, package_name: str) -> str:
    return f"""# {package.project_name}

Generated by the V-model agentic development engine.

## Commands

```powershell
python -m {package_name}.cli list-requirements
python -m {package_name}.cli trace
```

## Lifecycle Status

This is the first generated implementation scaffold. Requirements, tasks, tests, and release evidence are linked from the parent run artifacts.
"""


def _pyproject(package: ArtifactPackage, package_name: str) -> str:
    return f"""[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "{package_name.replace('_', '-')}"
version = "0.1.0"
description = "Generated project for {package.project_name}"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
{package_name.replace('_', '-')} = "{package_name}.cli:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

[tool.setuptools.packages.find]
include = ["{package_name}*"]
"""


def _cli_py(package_name: str) -> str:
    return f'''from __future__ import annotations

import argparse
import json
from importlib.resources import files


def load_requirements() -> list[dict[str, object]]:
    data = files("{package_name}.data").joinpath("requirements.json").read_text(encoding="utf-8")
    return json.loads(data)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generated V-model project CLI.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("list-requirements", help="List implemented software requirements.")
    subparsers.add_parser("trace", help="Print requirement trace summary.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    requirements = load_requirements()
    if args.command == "list-requirements":
        for requirement in requirements:
            print(f"{{requirement['id']}}: {{requirement['statement']}}")
        return 0
    if args.command == "trace":
        for requirement in requirements:
            print(f"{{requirement['id']}} -> tests planned -> verification pending")
        return 0
    raise ValueError(f"unsupported command: {{args.command}}")


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _test_cli(package_name: str) -> str:
    return f'''from {package_name}.cli import main


def test_list_requirements_outputs_records(capsys) -> None:
    assert main(["list-requirements"]) == 0
    output = capsys.readouterr().out
    assert "SW-001" in output


def test_trace_outputs_verification_status(capsys) -> None:
    assert main(["trace"]) == 0
    output = capsys.readouterr().out
    assert "verification pending" in output
'''


def _test_requirements(package_name: str, expected_count: int) -> str:
    return f'''from {package_name}.cli import load_requirements


def test_requirements_are_packaged() -> None:
    requirements = load_requirements()
    assert len(requirements) == {expected_count}
    assert all(requirement["id"].startswith("SW-") for requirement in requirements)
    assert all(requirement["acceptance_criteria"] for requirement in requirements)
'''
